# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :update_dependency do
    carthage(
        command: "update",
        platform: "iOS",
        cache_builds: true
    )
    rome(
        command: "upload",
        concurrently: "true"
    )
    if prompt(text: "Please enter 'y' after adding new frameworks in project. : ", boolean: true, ci_input:"y")
        sh("cd ..;carting update")
    end
  end
  lane :download_dependency do
    carthage(
      command: "update",
      platform: "iOS",
      no_build: true
    )
    rome(
        command: "download",
        concurrently: "true"
    )
    sh("cd ..;carting update")
  end
end
